# Site
name: "Cyrille Courtière Sailing"
title: "Cyrille Courtière Sailing"
description: "Mes aventures nautiques !"
logo: 'assets/images/boat-small-02.svg'
favicon: 'assets/images/boat-small-02.svg'
google_analytics: 'UA-xxxxxxxx-1'
include: ["_pages"]
permalink: /:title/
email: cyrille.courtiere@gmail.com
url: "https://sailing.cyrillecourtiere.com"

# Authors
authors:
  cyrille:
    name: Cyrille Courtière
    display_name: Cyrille
    avatar: assets/images/portrait-cyrille-small-3.jpg
    linkedin: https://www.linkedin.com/in/ccyrille/
    instagram: https://www.instagram.com/cyrille_sailing/
    email: cyrille.courtiere+sailingb@gmail.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
